### ISSUE TITLE
having error with pandas

### ISSUE THREAD

**Issue by mahmudulnothing** [ef1500/phonebrute#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\phonebrute-master\phonebrute.py", line 41, in <module>
    valid_numbers = lightning_search.generate_new_table()
  File "C:\Users\Administrator\Desktop\phonebrute-master\lightning_searcher.py", line 185, in generate_new_table
    new_table = new_table.append(temp_df, ignore_index=True)
  File "C:\Program Files\Python39\lib\site-packages\pandas\core\generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by ef1500** [comment]
Can you please tell me what command you used so I can attempt to replicate this?
